"""The `rig` command-line tool: list / call / monitor / stubs."""
from __future__ import annotations

import argparse
import sys
from typing import Optional

from . import __version__, connect
from ._wire import INT_KEYWORDS

_PY_TYPE = {
    "void": "None", "bool": "bool", "str": "str", "float": "float", "double": "float",
    "array": "list",
}


def _pytype(kw: str) -> str:
    if kw in INT_KEYWORDS:
        return "int"
    return _PY_TYPE.get(kw, "object")


def _add_conn_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--port", "-p", required=True, help="serial port (e.g. /dev/ttyACM0)")
    p.add_argument("--baud", "-b", type=int, default=115200)


def cmd_list(args) -> int:
    with connect(args.port, args.baud) as dev:
        names = dev.command_names
        w = max((len(n) for n in names), default=4)
        for n in names:
            sig = dev.signature(n)
            print(f"{n:<{w}}  {sig.get('ret','?'):<10}  ({', '.join(sig.get('args', []))})")
    return 0


def cmd_call(args) -> int:
    with connect(args.port, args.baud) as dev:
        try:
            resp = dev.call_raw(args.name, *args.tokens)
        except Exception as e:  # surface device/protocol errors plainly
            print(f"error: {e}", file=sys.stderr)
            return 1
        # unwrap the bare value when there are no extra fields, else show the dict
        print(resp["ret"] if resp.keys() == {"ret"} else resp)
    return 0


def cmd_monitor(args) -> int:
    def show(kind: str, payload) -> None:
        if kind == "console":
            print(f"  [dev] {payload}")
        elif kind == "event":
            print(f"  [event] {payload}")
        elif kind == "log":
            print(f"  [log] {payload}")
        else:  # response / malformed
            print(f"  {payload}")
    from .transport import SerialTransport
    from .device import Device
    dev = Device(SerialTransport(args.port, args.baud), on_line=show)
    try:
        dev.handshake()
    except Exception as e:
        print(f"warning: handshake failed: {e}", file=sys.stderr)
    print(f"riglink monitor on {args.port} — type commands, Ctrl-D to quit.")
    try:
        for line in sys.stdin:
            line = line.rstrip("\n")
            if line:
                dev.write_line(line)
    except KeyboardInterrupt:
        pass
    finally:
        dev.close()
    return 0


def cmd_stubs(args) -> int:
    with connect(args.port, args.baud) as dev:
        sigs = dev.list_commands()
    out = ["# Auto-generated by `rig stubs`. Do not edit.",
           "from typing import Any",
           "",
           "class RiglinkDevice:"]
    for name, sig in sorted(sigs.items()):
        ret = _pytype(sig.get("ret", "void"))
        argkws = sig.get("args", [])
        if argkws == ["..."]:
            params = "self, *args: Any"
        else:
            params = ", ".join(["self"] + [f"a{i}: {_pytype(k)}" for i, k in enumerate(argkws)])
        if "." in name:
            out.append(f"    # {name}({', '.join(argkws)}) -> {ret}   # call via dev.call_raw({name!r}, ...) or dev.{name.replace('.', '_')}(...)")
            attr = name.replace(".", "_")
        else:
            attr = name
        out.append(f"    def {attr}({params}) -> {ret}: ...")
    text = "\n".join(out) + "\n"
    if args.output and args.output != "-":
        with open(args.output, "w") as f:
            f.write(text)
        print(f"wrote {args.output}")
    else:
        sys.stdout.write(text)
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="rig", description="riglink command-line tool")
    p.add_argument("--version", action="version", version=f"riglink {__version__}")
    sub = p.add_subparsers(dest="cmd", required=True)

    pl = sub.add_parser("list", help="list the device's registered commands")
    _add_conn_args(pl); pl.set_defaults(func=cmd_list)

    pc = sub.add_parser("call", help="call a command and print the response")
    _add_conn_args(pc); pc.add_argument("name"); pc.add_argument("tokens", nargs="*"); pc.set_defaults(func=cmd_call)

    pm = sub.add_parser("monitor", help="interactive REPL + live events/logs")
    _add_conn_args(pm); pm.set_defaults(func=cmd_monitor)

    ps = sub.add_parser("stubs", help="emit a .pyi stub from rig.list")
    _add_conn_args(ps); ps.add_argument("--output", "-o", default="-"); ps.set_defaults(func=cmd_stubs)
    return p


def main(argv: Optional[list[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
